name: Build and Test CLI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore src/cli-sample.sln
      - name: Build
        run: dotnet build src/cli-sample.sln -c Release --no-restore
      - name: Test (TRX)
        run: |
          dotnet test src/cli-sample.sln -c Release --no-build \
            --logger trx --results-directory ./TestResults
      - name: Upload test-results artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: TestResults/**/*.trx
          if-no-files-found: warn
